dist: xenial

cache:
    apt: true

addons:
    apt:
        packages:
            - texlive
            - texlive-latex-extra
            - texlive-fonts-extra
            - texlive-lang-german
            - texlive-lang-english
            - lmodern
            - latex-xcolor
            #- python-wxgtk3.0
            #- xvfb                  # needed for headless wxGTK

script:
    # debian-supplied pandoc is very old --> install manually
    - wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
    - sudo dpkg -i pandoc-2.7.3-1-amd64.deb
    - rm pandoc-2.7.3-1-amd64.deb

    # build manual
    - cd manual
    - make all
    - mkdir build
    - cp manual.html build/index.html
    - cp manual.pdf build/
    - cp -r template/ build/
    - cp -r images/ build/

    # also deploy interactive BOM
    - cp ../build/*_ibom.html build

    # install KiCad
    #- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
    #- sudo apt update
    #- sudo apt install --no-install-recommends kicad

    # generate interactive BOM
    #- cd ..
    #- git clone https://github.com/openscopeproject/InteractiveHtmlBom bom-generator
    #- xvfb-run python bom-generator/InteractiveHtmlBom/generate_interactive_bom.py --no-browser kicad/mppt-1210-hus.kicad_pcb
    #- cp kicad/bom/ibom.html manual/build/bom.html

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_REPO_TOKEN
    local-dir: manual/build
    keep-history: false
    on:
        branch: main
